# -*- coding: utf-8 -*-
"""Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LyxOdykT8bKuILFBSRbR0M8jMWIbZhu-
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
from torchvision import datasets, transforms, models
from torch.utils.data.sampler import SubsetRandomSampler
import torch.nn as nn
import torch.nn.functional as F

pip install nb_black

# Commented out IPython magic to ensure Python compatibility.
# %load_ext nb_black

transform = transforms.Compose([transforms.Resize(255), transforms.CenterCrop(244), transforms.ToTensor()])

dataset = datasets.ImageFolder("https://www.kaggle.com/datasets/ahilaprem/mepco-tropic-leaf", transform=transform)