# Generated by Django 4.2 on 2023-04-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processimage',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processimage',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
